# Generated by Django 3.2.25 on 2025-02-17 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=90)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='diet_plan_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=1, max_length=100)),
                ('Date', models.DateField()),
                ('Time', models.TimeField(max_length=100)),
                ('Dietplan', models.CharField(max_length=500)),
                ('Gender', models.CharField(max_length=100)),
                ('Obicity', models.CharField(max_length=100)),
                ('Bloodpressure', models.CharField(max_length=100)),
                ('Diabetes', models.CharField(max_length=100)),
                ('Cholestrol', models.CharField(max_length=100)),
                ('Alcoholabuse', models.CharField(max_length=100)),
                ('Druguse', models.CharField(max_length=100)),
                ('Smoking', models.CharField(max_length=100)),
                ('Headaches', models.CharField(max_length=100)),
                ('Asthma', models.CharField(max_length=100)),
                ('Heartproblem', models.CharField(max_length=100)),
                ('Cancer', models.CharField(max_length=100)),
                ('Stroke', models.CharField(max_length=100)),
                ('Kidney', models.CharField(max_length=100)),
                ('Liver', models.CharField(max_length=100)),
                ('Depression', models.CharField(max_length=100)),
                ('Allergies', models.CharField(max_length=100)),
                ('Arthritis', models.CharField(max_length=100)),
                ('Pregnancy', models.CharField(max_length=100)),
                ('bmi', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=80)),
                ('phone', models.BigIntegerField()),
                ('image', models.FileField(upload_to='')),
                ('department', models.CharField(max_length=90)),
                ('qualification', models.CharField(max_length=80)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='hospital_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('website', models.CharField(max_length=90)),
                ('contactno', models.BigIntegerField()),
                ('place', models.CharField(max_length=90)),
                ('pin', models.IntegerField()),
                ('post', models.CharField(max_length=90)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='lab_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=90)),
                ('website', models.CharField(max_length=90)),
                ('contactno', models.BigIntegerField()),
                ('place', models.CharField(max_length=90)),
                ('pin', models.IntegerField()),
                ('post', models.CharField(max_length=90)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=80)),
                ('type', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=80)),
                ('place', models.CharField(max_length=90)),
                ('dob', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('pin', models.IntegerField()),
                ('post', models.CharField(max_length=90)),
                ('image', models.FileField(upload_to='')),
                ('lab', models.CharField(default='none', max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthify.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='test_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=90)),
                ('result', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('LAB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthify.lab_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthify.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='schedule_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fromtime', models.TimeField()),
                ('totime', models.TimeField()),
                ('DOCTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthify.doctor_table')),
            ],
        ),
        migrations.CreateModel(
            name='review_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=90)),
                ('rating', models.CharField(max_length=90)),
                ('date', models.DateField()),
                ('HOSPITAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthify.hospital_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthify.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='prescription_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.CharField(max_length=90)),
                ('quantity', models.IntegerField()),
                ('days', models.IntegerField()),
                ('morning', models.CharField(max_length=90)),
                ('afternoon', models.CharField(max_length=90)),
                ('night', models.CharField(max_length=90)),
                ('date', models.DateField()),
                ('BOOKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthify.booking_table')),
            ],
        ),
        migrations.AddField(
            model_name='lab_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthify.login_table'),
        ),
        migrations.AddField(
            model_name='hospital_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthify.login_table'),
        ),
        migrations.AddField(
            model_name='doctor_table',
            name='HOSPITAL',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthify.hospital_table'),
        ),
        migrations.AddField(
            model_name='doctor_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthify.login_table'),
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=90)),
                ('reply', models.CharField(max_length=90)),
                ('date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthify.user_table')),
            ],
        ),
        migrations.AddField(
            model_name='booking_table',
            name='SCHEDULE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthify.schedule_table'),
        ),
        migrations.AddField(
            model_name='booking_table',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthify.user_table'),
        ),
    ]
