# Generated by Django 3.2.25 on 2025-02-17 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Healthify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet_plan_table',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='diet_plan_table',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='diet_plan_table',
            name='Time',
        ),
    ]
