# Generated by Django 3.2.25 on 2025-02-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthify', '0002_auto_20250217_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet_plan_table',
            name='Dietplan',
            field=models.FileField(upload_to=''),
        ),
    ]
