# Generated by Django 3.2.25 on 2025-02-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthify', '0003_alter_diet_plan_table_dietplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_table',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
