# Generated by Django 3.2.25 on 2025-02-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthify', '0004_alter_prescription_table_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='complaint_table',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='review_table',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='test_table',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
