# Generated by Django 3.2.25 on 2025-02-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthify', '0005_auto_20250221_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='complaint_table',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='prescription_table',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='review_table',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='test_table',
            name='date',
            field=models.DateField(),
        ),
    ]
