# Generated by Django 3.2.25 on 2025-02-28 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Healthify', '0006_auto_20250221_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='reminder_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning', models.TimeField(max_length=90)),
                ('afternoon', models.TimeField(max_length=90)),
                ('night', models.TimeField(max_length=90)),
                ('PRESCRIPTION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthify.booking_table')),
            ],
        ),
    ]
