# Generated by Django 3.2.25 on 2025-02-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthify', '0007_reminder_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder_table',
            name='afternoon',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='reminder_table',
            name='morning',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='reminder_table',
            name='night',
            field=models.CharField(max_length=90),
        ),
    ]
