# Generated by Django 3.2.25 on 2025-02-28 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Healthify', '0008_auto_20250228_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder_table',
            name='PRESCRIPTION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Healthify.prescription_table'),
        ),
        migrations.AlterField(
            model_name='reminder_table',
            name='afternoon',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder_table',
            name='morning',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder_table',
            name='night',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
