# Generated by Django 3.2.25 on 2025-02-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Healthify', '0009_auto_20250228_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_table',
            name='notificationstatus',
            field=models.CharField(default='notopened', max_length=50),
        ),
    ]
